server:
  port: 9003
spring:
  application:
    name: mo-product-service
  cloud:
    nacos: #注册中心地址
      discovery:
        server-addr: 39.108.182.26:8848
  datasource: #数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.182.26:3306/moshop_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mo12345
  redis:   #Redis
    host: 39.108.182.26
    port: 8000
    password: 123456
  rabbitmq:   #消息队列
    host: 39.108.182.26
    port: 5672
    virtual-host: /
    username: admin
    password: mo12345
    listener:  #开启手动确认消息
      simple:
        acknowledge-mode: manual
  flyway:
    enabled: true
    encoding: utf-8
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
    table: flyway_schema_version_history
#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
    #nacos日志问题
    com.alibaba.nacos.client.config.impl: WARN
#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  product_release_delay_queue: product.release.delay.queue
  #延迟队列的消息过期后转发的队列-死信队列
  product_release_queue: product.release.queue
  #交换机
  product_event_exchange: product.event.exchange
  #进入延迟队列的路由key
  product_release_delay_routing_key: product.release.delay.routing.key
  #消息过期，进入释放死信队列的key
  product_release_routing_key: product.release.routing.key
  #消息过期时间,毫秒,测试改为15秒-15000
  ttl: 360000 # 锁定商品的时间为6分钟