server:
  port: 9005
spring:
  application:
    name: mo-order-service
  cloud:
    nacos: #注册中心地址
      discovery:
        server-addr: 39.108.182.26:8848
    sentinel: #限流配置
      transport:
        dashboard: 39.108.182.26:8858 #dashboard: 8858 控制台端口
        port: 9999
      #流控规则持久化到nacos配置中心
      datasource:
        ds1: #自定义id
          nacos:
            server-addr: 39.108.182.26:8848
            data-id: ${spring.application.name}-${spring.profiles.active}.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  datasource: #数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.182.26:3306/moshop_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mo12345
  redis:   #Redis
    host: 39.108.182.26
    port: 8000
    password: mo12345
  rabbitmq:   #消息队列
    host: 39.108.182.26
    port: 5672
    virtual-host: /
    username: admin
    password: mo12345
    listener:  #开启手动确认消息
      simple:
        acknowledge-mode: manual
  flyway:
    enabled: true
    encoding: utf-8
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
    table: flyway_schema_version_history
#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
    #nacos日志问题
    com.alibaba.nacos.client.config.impl: WARN
#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  order_close_delay_queue: order.close.delay.queue
  #延迟队列的消息过期后转发的队列-死信队列
  order_close_queue: order.close.queue
  #交换机
  order_event_exchange: order.event.exchange
  #进入延迟队列的路由key
  order_close_delay_routing_key: order.close.delay.routing.key
  #消息过期，进入释放死信队列的key
  order_close_routing_key: order.close.routing.key
  #消息过期时间,毫秒,测试改为15秒-15000
  ttl: 300000 # 订单5分钟超时未支付则关闭
#支付宝配置
alipay:
  #支付成功的跳转页面
  success_return_url: https://xdclass.net
  #支付宝通知回调接口，蚂蚁金服开放平台应用后台也需要配置这个地址
  #callback_url: http://moshop.ngrok2.xiaomiqiu.cn/api/pay/v1/callback/alipay
  #引入gateway后需要转发到网关地址
  callback_url: http://moshop.ngrok2.xiaomiqiu.cn/order-server/api/pay/v1/callback/alipay